version: '3'

services:
    db: # hostname
        image: postgres
        environment: # default user is postgres
            POSTGRES_PASSWORD: '12345'
            POSTGRES_DB: 'prisma-node' #database name
        ports:
            - '5432:5432'
